[package]
name = "magnolia-protocol"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
magnolia-domain = { path = "../magnolia-domain" }
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
hex.workspace = true
