[package]
name = "magnolia-audio"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
magnolia-domain = { path = "../magnolia-domain" }
rtrb.workspace = true
serde.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
pipewire = "0.9.2"
