[package]
name = "magnolia-application"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
event-listener.workspace = true
magnolia-client = { path = "../magnolia-client" }
magnolia-domain = { path = "../magnolia-domain" }
magnolia-protocol = { path = "../magnolia-protocol" }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
futures.workspace = true
